name    'cmurphy-puppetanalytics'
version '0.1.0'
source 'https://github.com/cmurphy/puppet-puppetanalytics'
author 'cmurphy'
license 'Apache License, Version 2.0'
summary 'Puppet module for https://github.com/nibalizer/puppet-analytics'
project_page 'https://github.com/nibalizer/puppet-analytics'

dependency 'puppetlabs/vcsrepo'
dependency 'jfryman/nginx'
dependency 'stankevich/python'
